# Generated by Django 3.1.7 on 2021-04-05 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='total',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='AchieveManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.IntegerField(default=0)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='achieved_user',
            field=models.ManyToManyField(related_name='achieved', through='account.AchieveManage', to=settings.AUTH_USER_MODEL),
        ),
    ]
