# Generated by Django 3.1.7 on 2021-03-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='temp_nick', max_length=30),
        ),
    ]
