# Generated by Django 3.1.7 on 2021-03-30 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0001_initial'),
        ('account', '0002_user_nickname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recent_learned_lc',
            new_name='RecentLearnedLc',
        ),
    ]
