# Generated by Django 3.1.7 on 2021-03-31 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210330_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='learned_kw',
        ),
    ]
