# Generated by Django 3.1.7 on 2021-04-01 04:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210331_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='image',
            new_name='imgurl',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='achieved',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='orm',
        ),
        migrations.AddField(
            model_name='achievement',
            name='achieved_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AchievedManage',
        ),
    ]
