# Generated by Django 3.1.7 on 2021-04-01 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210401_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achieved_user',
            field=models.ManyToManyField(related_name='achieved', to=settings.AUTH_USER_MODEL),
        ),
    ]
