# Generated by Django 3.1.7 on 2021-04-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210401_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='imgurl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
