# Generated by Django 3.1.7 on 2021-04-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210401_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='done',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='great_dsc',
            field=models.TextField(default='Need to add'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='great_eng',
            field=models.CharField(default='Need to add', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='great_kor',
            field=models.CharField(default='Need to add', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievement',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
