# Generated by Django 3.1.7 on 2021-03-29 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpct',
            name='cs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.cs'),
        ),
        migrations.AlterField(
            model_name='cpct',
            name='main_kw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.kw'),
        ),
        migrations.CreateModel(
            name='Lc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_kw_index', models.IntegerField(null=True)),
                ('main_kw_word', models.TextField(null=True)),
                ('meaning', models.TextField(null=True)),
                ('before_kor', models.TextField()),
                ('before_eng', models.TextField()),
                ('cpct_kor', models.TextField()),
                ('cpct_eng', models.TextField()),
                ('after_kor', models.TextField()),
                ('after_eng', models.TextField()),
                ('example', models.TextField()),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.cs')),
                ('main_kw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.kw')),
            ],
        ),
    ]
