# Generated by Django 3.1.7 on 2021-03-31 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kw',
            old_name='content',
            new_name='content_kor',
        ),
        migrations.AddField(
            model_name='kw',
            name='content_eng',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
