# Generated by Django 3.1.7 on 2021-03-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0002_auto_20210331_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lc',
            old_name='example',
            new_name='example_kor',
        ),
        migrations.RenameField(
            model_name='lc',
            old_name='main_kw_word',
            new_name='main_kw_kor',
        ),
        migrations.RemoveField(
            model_name='lc',
            name='main_kw',
        ),
        migrations.AddField(
            model_name='lc',
            name='example_eng',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lc',
            name='main_kw_eng',
            field=models.TextField(null=True),
        ),
    ]
