# Generated by Django 3.1.7 on 2021-03-31 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0003_auto_20210331_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='lc',
            name='main_kw',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='klass.kw'),
            preserve_default=False,
        ),
    ]
