# Generated by Django 3.1.7 on 2021-04-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0005_auto_20210401_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cs',
            old_name='name',
            new_name='name_kor',
        ),
        migrations.AddField(
            model_name='cs',
            name='name_eng',
            field=models.CharField(default='Need to Add', max_length=100),
            preserve_default=False,
        ),
    ]
