# Generated by Django 3.1.7 on 2021-04-02 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kor', models.CharField(max_length=100)),
                ('name_eng', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
                ('imgurl', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_kor', models.CharField(max_length=30)),
                ('content_eng', models.CharField(blank=True, max_length=30, null=True)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_kw_index', models.IntegerField(null=True)),
                ('main_kw_kor', models.TextField(null=True)),
                ('main_kw_eng', models.TextField(null=True)),
                ('meaning', models.TextField(null=True)),
                ('before_kor', models.TextField()),
                ('before_eng', models.TextField()),
                ('cpct_kor', models.TextField()),
                ('cpct_eng', models.TextField()),
                ('after_kor', models.TextField()),
                ('after_eng', models.TextField()),
                ('example_kor', models.TextField()),
                ('example_eng', models.TextField(null=True)),
                ('imgurl', models.TextField()),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.cs')),
                ('main_kw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.kw')),
            ],
        ),
        migrations.CreateModel(
            name='Cpct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor', models.TextField()),
                ('eng', models.TextField()),
                ('cs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.cs')),
                ('main_kw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klass.kw')),
            ],
        ),
        migrations.CreateModel(
            name='Cpcq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor', models.TextField()),
                ('eng', models.TextField()),
                ('kcq', models.ManyToManyField(related_name='contained_cpcq', to='klass.Kw')),
            ],
        ),
    ]
