# Generated by Django 3.1.7 on 2021-04-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klass', '0002_auto_20210402_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kw',
            name='content_eng',
        ),
    ]
